#! /usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2003, 2005 by Germanischer Lloyd

# ======================================================================
# Task      numerical diff for text files
# ----------------------------------------------------------------------
# Author    Berthold Höllmann <hoel@GL-Group.com>
# Project   numdiff
# ======================================================================

from numdiff import Main
MAIN = Main()
raise SystemExit(MAIN())

# Local Variables:;
# compile-command:"make -C ../test test";
# End:;
